- name: Create output dir
  ansible.builtin.file:
    path: "{{ launchertw_build_output_dir }}"
    state: directory
    mode: 0750
  when: launchertw_build_output_dir != 'TMP'

- name: Create temp directory
  block:
    - name: Create temp directory
      ansible.builtin.tempfile:
        path: /tmp
        prefix: LauncherTW_
        state: directory
      register: _temp_dir
    - name: Set output to temp directory
      ansible.builtin.set_fact:
        launchertw_build_output_dir: "{{ _temp_dir.path }}"
  when: launchertw_build_output_dir == 'TMP'

- name: Create css dir in output dir
  ansible.builtin.file:
    path: "{{ launchertw_build_output_dir }}/css"
    mode: 0750
    state: directory
  register: _css_dir

- name: Copy img dir to output dir
  ansible.builtin.copy:
    src: img
    dest: "{{ launchertw_build_output_dir }}"
    mode: 0750
- name: Copy robots.txt to output dir
  ansible.builtin.copy:
    src: robots.txt
    dest: "{{ launchertw_build_output_dir }}"
    mode: 0640

- name: Build Tailwind CSS
  ansible.builtin.command:
    chdir: '{{ role_path }}'
    argv:
      - npx
      - tailwindcss
      - -m
      - -c
      - files/tailwind.config.js
      - -i
      - files/css/launcher.css
      - -o
      - "{{ _css_dir.path }}/launcher.min.css"
  changed_when: true

- name: Get checksum of css output
  ansible.builtin.stat:
    path: "{{ _css_dir.path }}/launcher.min.css"
    checksum_algorithm: md5
  register: _css_stat
- name: Copy css output to include checksum
  ansible.builtin.copy:
    src: "{{ _css_dir.path }}/launcher.min.css"
    dest: "{{ _css_dir.path }}/launcher.min.{{ _css_stat.stat.checksum }}.css"
    mode: 0640
- name: Remove original css output
  ansible.builtin.file:
    path: "{{ _css_dir.path }}/launcher.min.css"
    state: absent

- name: Install HTML to temp dir
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ launchertw_build_output_dir }}/index.html"
    mode: 0640
