- name: Create output dir
  ansible.builtin.file:
    path: "{{ build_output_dir }}"
    state: directory
    mode: 0750
  when: build_output_dir != 'TMP'

- name: Create temp directory
  block:
    - name: Create temp directory
      ansible.builtin.tempfile:
        path: /tmp
        prefix: LauncherTW_
        state: directory
      register: _temp_dir
    - name: Set output to temp directory
      ansible.builtin.set_fact:
        build_output_dir: "{{ _temp_dir.path }}"
  when: build_output_dir == 'TMP'

- name: Install HTML to temp dir
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ build_output_dir }}/index.html"
    mode: 0640

- name: Build Tailwind CSS
  ansible.builtin.command:
    # TODO: get dir of role
    # TODO: install tailwindcss-cli somewhere sensible
    chdir: roles/LauncherTW
    argv:
      - npx
      - tailwindcss
      - -m
      - -c
      - files/tailwind.config.js
      - -i
      - files/css/launcher.css
      - -o
      - "{{ build_output_dir }}/launcher.min.css"
  changed_when: true
