# When operation = 'build', display temp dir location
- name: Display build output dir
  ansible.builtin.pause:
    prompt: |
      LauncherTW has been built successfully! See the build at
      {{ launchertw_build_output_dir }}
      Press Enter to continue...
  when: launchertw_operation == 'build'

# When operation = 'deploy', remove temp dir after deployment
- name: Post-deploy delete temp dir
  ansible.builtin.file:
    path: "{{ launchertw_build_output_dir }}"
    state: absent
  when: launchertw_operation == 'deploy' and _temp_dir.path is defined
