# When operation = 'build', display temp dir location
- name: Display temp dir location
  ansible.builtin.pause:
    prompt: |
      LauncherTW has been built successfully! See the build at
      {{ launchertw_build_output_dir }}
      Press Enter to continue...
  when: launchertw_operation == 'build'

# When operation = 'deploy', remove temp dir after deployment
- name: Post-deploy cleanup
  when: launchertw_operation == 'deploy'
  block:
    - name: Delete temp dir
      ansible.builtin.file:
        path: "{{ launchertw_build_output_dir }}"
        state: absent
      when: _temp_dir.path is defined
    - name: Display deployment status
      ansible.builtin.debug:
        msg: "LauncherTW has been deployed!"
