---
name: dependency review
on: # yamllint disable-line rule:truthy
  pull_request:
jobs:
  dependency-review:
    name: dependency review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
